sudo: required
language: python
python:
  - "3.4"
  - "3.5"
# command to install dependencies
install:
  - sudo pip --user install .
# command to run tests
script:
  - burp-reports --burpui_api dummy --report outdated