language: python
dist: trusty
python:
  - "3.4"
  - "3.5"
# command to install dependencies
install:
  - pip install rstcheck
  - pip install .
# command to run tests
script:
  - burp-reports --burpui_apiurl dummy --report outdated
  - burp-reports --burpui_apiurl dummy --report outdated --detail
  - time burp-reports --burpui_apiurl dummy --report inventory -i burp_reports/data/test_inventory.csv -o test.csv
  - cat test.csv
  - burp-reports --burpui_apiurl dummy -c test1.conf --write_config
  - burp-reports --burpui_apiurl https://admin:admin@demo.ziirish.me/api/ --report outdated --detail
  - burp-reports --burpui_apiurl https://admin:admin@demo.ziirish.me/api/ --debug --detail
  - time burp-reports -ui dummy --report inventory -i https://raw.githubusercontent.com/pablodav/burp_server_reports/master/burp_reports/data/test_inventory.csv -o test_from_url.csv
  - burp-reports --burpui_apiurl https://admin:admin@demo.ziirish.me/api/ --report inventory -i burp_reports/data/test_inventory.csv -o test_ui.csv
  - cat test_ui.csv
  - py.test

after_success:
  - pip install pytest-cov
  - py.test --cov=burp_reports
  - bash <(curl -s https://codecov.io/bash)
