language: python
dist: trusty
python:
  - "3.4"
  - "3.5"
# command to install dependencies
install:
  - pip install .
# command to run tests
script:
  - burp-reports --burpui_apiurl dummy --report outdated
  - burp-reports --burpui_apiurl dummy --report outdated --detail
  - burp-reports --burpui_apiurl dummy --report inventory -i burp_reports/data/test_inventory.csv -o test.csv
  - burp-reports --burpui_apiurl dummy -c test1.conf --write_config
  - burp-reports --burpui_apiurl https://admin:admin@demo.ziirish.me/api/ --report outdated --detail
  - burp-reports --burpui_apiurl https://admin:admin@demo.ziirish.me/api/ --debug --detail
  - burp-reports --burpui_apiurl https://admin:admin@demo.ziirish.me/api/ --report inventory -i burp_reports/data/test_inventory.csv -o test_ui.csv
  - cat test_ui.csv
