language: python
python:
  - "3.4"
  - "3.5"
# command to install dependencies
install:
  - pip install --user .
# command to run tests
script:
  - ~/.local/bin/burp-reports --burpui_api dummy --report outdated