sudo: required
language: python
python:
  - "3.4.3"
services:
  - docker
env:
  TOX_PY34='3.4.3'
  TOX_PY35='3.5.2'
  TOX_PY36='3.6.1'
before_install:
  - sudo apt-get -qq update
  - pip -V
  - pip install -U pip
  - pip install --upgrade tox
  - pip install --upgrade tox-pyenv
  - pyenv local $TOX_PY34 $TOX_PY35 $TOX_PY36
  - docker pull greenmail/standalone:1.5.5
  - docker run -d -p 3025:3025 -p 3110:3110 -p 3143:3143 -p 3465:3465 -p 3993:3993 -p 3995:3995 greenmail/standalone:1.5.5
# install:
script:
  - tox -v --recreate
