language: python
dist: trusty
python:
  - "3.4"
  - "3.5"
# command to install dependencies
install:
  - pip install .
  - pip install dist/burp_reports-1.0rc1-py3-none-any.whl
# command to run tests
script:
  - python burp-reports/__main__.py --burpui_api dummy --report outdated